// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Config from "./components/Config.bs.js";
import * as Router from "./Router.bs.js";
import * as NotFound from "./components/NotFound.bs.js";
import * as GqlExamples from "./gql-exampls--reference-only/GqlExamples.bs.js";
import * as LoginJs from "./deprecated/login.js";

var make = LoginJs.default;

var LoginScreen = {
  make: make
};

function App(Props) {
  var route = Router.useRouter(undefined);
  if (route === undefined) {
    return React.createElement(NotFound.make, {});
  }
  switch (route) {
    case /* Main */0 :
        return React.createElement(make, {});
    case /* Config */1 :
        return React.createElement(Config.make, {});
    case /* GqlExamplesPage */2 :
        return React.createElement(GqlExamples.make, {});
    
  }
}

var make$1 = App;

export {
  LoginScreen ,
  make$1 as make,
  
}
/* make Not a pure module */
