// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as About from "./components/About.bs.js";
import * as Login from "./components/Login.bs.js";
import * as React from "react";
import * as Config from "./components/Config.bs.js";
import * as Router from "./Router.bs.js";
import * as NotFound from "./components/NotFound.bs.js";
import * as GqlExamples from "./gql-exampls--reference-only/GqlExamples.bs.js";

function App(Props) {
  var route = Router.useRouter(undefined);
  var tmp;
  if (route !== undefined) {
    switch (route) {
      case /* Main */0 :
          tmp = React.createElement(Login.make, {
                children: React.createElement("p", undefined, "Home page")
              });
          break;
      case /* Config */1 :
          tmp = React.createElement(Login.make, {
                children: React.createElement(Config.make, {})
              });
          break;
      case /* About */2 :
          tmp = React.createElement(About.make, {});
          break;
      case /* GqlExamplesPage */3 :
          tmp = React.createElement(GqlExamples.make, {});
          break;
      
    }
  } else {
    tmp = React.createElement(NotFound.make, {});
  }
  return React.createElement("div", {
              className: "app"
            }, tmp);
}

var make = App;

export {
  make ,
  
}
/* About Not a pure module */
