// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Mutation = require("./hooksUsage/Mutation.bs.js");
var Query_Lazy = require("./hooksUsage/Query_Lazy.bs.js");
var ClientBasics = require("./clientUsage/ClientBasics.bs.js");
var Query_Typical = require("./hooksUsage/Query_Typical.bs.js");
var Query_OverlySimple = require("./hooksUsage/Query_OverlySimple.bs.js");

function App(Props) {
  return React.createElement("div", undefined, React.createElement("h2", undefined, "Simple Query"), React.createElement(Query_OverlySimple.make, {}), React.createElement("h2", undefined, "Typical Query"), React.createElement(Query_Typical.make, {}), React.createElement("h2", undefined, "Lazy Query"), React.createElement(Query_Lazy.make, {}), React.createElement("h2", undefined, "Mutation"), React.createElement(Mutation.make, {}), React.createElement("h2", undefined, "Client Methods"), React.createElement(ClientBasics.make, {}));
}

var make = App;

exports.make = make;
/* react Not a pure module */
