// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as React from "react";
import * as Client from "./Client.bs.js";
import * as ReactDOMRe from "reason-react/src/legacy/ReactDOMRe.bs.js";
import * as Client$1 from "@apollo/client";

ReactDOMRe.renderToElementWithId(React.createElement(Client$1.ApolloProvider, {
          client: Client.instance,
          children: React.createElement(App.make, {})
        }), "root");

export {
  
}
/*  Not a pure module */
